package WrapperDSL.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SEnumOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;

public class ObstacleAvoidanceSensorStateConditionalExpression_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    if (SPropertyOperations.getEnum(ctx.getPrimaryInput(), PROPS.state$72Y8) == SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3e1c68c4ebe640bdL, 0xa27fe74585aa2487L, 0x53e04e3aef1648efL, "WrapperDSL.structure.ObstacleAvoidanceGetEnum"), 0x53e04e3aef1648f8L, "ERROR")) {
      if (SPropertyOperations.getEnum(ctx.getPrimaryInput(), PROPS.operator$72J7) == SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3e1c68c4ebe640bdL, 0xa27fe74585aa2487L, 0x53e04e3aef1642e8L, "WrapperDSL.structure.EqualityOperatorEnum"), 0x53e04e3aef1642e9L, "iqual")) {
        tgs.append("            (");
        tgs.newLine();
        tgs.append("            (((Drone)thisJoinPoint.getArgs()[0]).getCollisionState() == CollisionStateEnum.FAILURE)");
        tgs.newLine();
        tgs.append("            ||");
        tgs.newLine();
        tgs.append("            (((Drone)thisJoinPoint.getArgs()[0]).getCollisionState() == CollisionStateEnum.OFF)");
        tgs.newLine();
        tgs.append("            )");
      } else {
        tgs.append("?");
        tgs.newLine();
      }
    }
  }

  private static final class PROPS {
    /*package*/ static final SProperty state$72Y8 = MetaAdapterFactory.getProperty(0x3e1c68c4ebe640bdL, 0xa27fe74585aa2487L, 0x53e04e3aef164338L, 0x7fd8262c2025d74eL, "state");
    /*package*/ static final SProperty operator$72J7 = MetaAdapterFactory.getProperty(0x3e1c68c4ebe640bdL, 0xa27fe74585aa2487L, 0x53e04e3aef164338L, 0x7fd8262c2025d74dL, "operator");
  }
}
