package WrapperDSL.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SEnumOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;

public class SmokerDetectorResultConditionalExpression_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    if (SPropertyOperations.getEnum(ctx.getPrimaryInput(), PROPS.result$h6aU) == SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3e1c68c4ebe640bdL, 0xa27fe74585aa2487L, 0x7fd8262c2025d942L, "WrapperDSL.structure.SmokerStateResultEnum"), 0x7fd8262c2025d943L, "DETECTED")) {
      if (SPropertyOperations.getEnum(ctx.getPrimaryInput(), PROPS.operator$h5GS) == SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x3e1c68c4ebe640bdL, 0xa27fe74585aa2487L, 0x53e04e3aef1642e8L, "WrapperDSL.structure.EqualityOperatorEnum"), 0x53e04e3aef1642e9L, "iqual")) {
        tgs.append("            executingFrameWork == false");
      }
    }
  }

  private static final class PROPS {
    /*package*/ static final SProperty result$h6aU = MetaAdapterFactory.getProperty(0x3e1c68c4ebe640bdL, 0xa27fe74585aa2487L, 0x7fd8262c2025d93cL, 0x7fd8262c2025d93fL, "result");
    /*package*/ static final SProperty operator$h5GS = MetaAdapterFactory.getProperty(0x3e1c68c4ebe640bdL, 0xa27fe74585aa2487L, 0x7fd8262c2025d93cL, 0x7fd8262c2025d93dL, "operator");
  }
}
